### ISSUE TITLE
Issue while joining between a joined table (A:join:B) and one of the joining tables(A)

### ISSUE THREAD

**Issue by bewakes** [the-dive/dive-server#74]
```dive_server_1  | Traceback (most recent call last):
dive_server_1  |   File "/usr/local/lib/python3.10/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
dive_server_1  |     return executor.execute(resolve_fn, source, info, **args)
dive_server_1  |   File "/usr/local/lib/python3.10/site-packages/graphql/execution/executors/sync.py", line 16, in execute
dive_server_1  |     return fn(*args, **kwargs)
dive_server_1  |   File "/code/utils/decorators.py", line 27, in mutate
dive_server_1  |     return f(instance, root, info, id, *args, **kwargs)
dive_server_1  |   File "/code/apps/core/mutations.py", line 276, in mutate
dive_server_1  |     new_cols, new_rows, _ = perform_hash_join_(
dive_server_1  |   File "/code/apps/core/utils.py", line 147, in perform_hash_join_
dive_server_1  |     source_data["columns"],
dive_server_1  | TypeError: 'NoneType' object is not subscriptable
```

**Comment by bewakes** [comment]
Seems to be related to #75
